spring:
  profiles:
    active:
    - dev

---
server:
  port: 7001
spring:
  profiles: dev
eureka:
  instance:
    #hostname: localhost
    hostname: eureka7001.com   #集群配置
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

---
server:
  port: 7002
spring:
  profiles: test
eureka:
  instance:
    #hostname: localhost
    hostname: eureka7002.com   #集群配置
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka