spring:
  profiles:
    active:
    - dev

---
server:
  port: 8201
spring:
  profiles: dev
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

---
server:
  port: 8202
spring:
  profiles: test
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka