spring:
  profiles:
    active:
    - dev

---
server:
  port: 8002
spring:
  profiles: dev
  application:
    name: user-provide8002
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud
    username: root
    password: 123456
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka
      #defaultZone: http://www.eureka7001.com:7001/eureka,http://www.eureka7002.com:7002/eureka
  instance:
    instance-id: cloud-user-provide8002
    prefer-ip-address: true
info:
  bulid.artifactId: $project.artifactId$
  bulid.version: $project.version$
  server.name: user-provide8002

---
server:
  port: 8003
spring:
  profiles: test
  application:
    name: user-provide8003
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud
    username: root
    password: 123456
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka
      #defaultZone: http://www.eureka7001.com:7001/eureka,http://www.eureka7002.com:7002/eureka
  instance:
    instance-id: cloud-user-provide8003
    prefer-ip-address: true
info:
  bulid.artifactId: $project.artifactId$
  bulid.version: $project.version$
  server.name: user-provide8003